# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87feb97ac87fa50eef77fba882fd50013539ea8f476324a7374c01b2e149ef0138feabdefec83b1d1917dca46896b5af988038caf02a81a6118db93d89a62088

test:
  secret_key_base: 4c673d3bb9ae780f7f7a8706104da30509d853029219e3960d8cea35a3f740d11f0bc5dc915933ac789bc78a436732382759db36c60b733cf816465d21dbbc45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
